PRIVATE_KEY = 'q1oukwa2hzsoxg4j7arvd6q67ik'
APP_NAME = 'unittest_2'

DELAY_TO_QUERY_TEMPLATES = 30
DELAY_TO_QUERY_INCIDENTS = 60
DELAY_TO_QUERY_BACKEND = max(DELAY_TO_QUERY_INCIDENTS, DELAY_TO_QUERY_TEMPLATES)
