MAGIC_LINK = 'https://logsight.ai//auth/activate/ae9gldsevubwtahqx9gxysyc2u_n32bp7pdlgjdsoqhmob9o4jdeek'
MAGIC_LINK = 'http://wally113.cit.tu-berlin.de:4200/auth/activate/jvvggnfy7bh6vwcnpc4kdy0luuw_raghsmqjmftu10fngvb89a7fgoo'
MAGIC_LINK = 'http://wally113.cit.tu-berlin.de:4200/auth/activate/vzppoaragimcf738in9qn4klbzi'
MAGIC_LINK = 'https://demo.logsight.ai/auth/login/2/cryciuuh436ho7i08in3kyt3ym'
PRIVATE_KEY = 'vrrrjbamjrvfj0cvmujz3dgax2i'
EMAIL = 'jorge.cardoso.pt@gmail.com'
