name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build Python distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install flake8
        run: |
          pip install flake8

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"

#      - name: Run tox
#        run: |
#            python -m tox

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#      - name: Test with unittest
#        run: |
#          export PYTHONPATH=$PYTHONPATH:/home/runner/work/logsight-python-sdk/logsight-python-sdk
#          cd tests
#          python -m unittest discover
#          cd ..

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist
